
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TdistrictService", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TdistrictService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateDistrict", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.UpdateDistrict")
    @ResponseWrapper(localName = "updateDistrictResponse", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.UpdateDistrictResponse")
    @Action(input = "http://AddressEx.addressService.service.clinicawebservice.com/TdistrictService/updateDistrictRequest", output = "http://AddressEx.addressService.service.clinicawebservice.com/TdistrictService/updateDistrictResponse")
    public boolean updateDistrict(
        @WebParam(name = "arg0", targetNamespace = "")
        TdistrictDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertDistrict", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.InsertDistrict")
    @ResponseWrapper(localName = "insertDistrictResponse", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.InsertDistrictResponse")
    @Action(input = "http://AddressEx.addressService.service.clinicawebservice.com/TdistrictService/insertDistrictRequest", output = "http://AddressEx.addressService.service.clinicawebservice.com/TdistrictService/insertDistrictResponse")
    public boolean insertDistrict(
        @WebParam(name = "arg0", targetNamespace = "")
        TdistrictDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteDistrict", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.DeleteDistrict")
    @ResponseWrapper(localName = "deleteDistrictResponse", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.DeleteDistrictResponse")
    @Action(input = "http://AddressEx.addressService.service.clinicawebservice.com/TdistrictService/deleteDistrictRequest", output = "http://AddressEx.addressService.service.clinicawebservice.com/TdistrictService/deleteDistrictResponse")
    public boolean deleteDistrict(
        @WebParam(name = "arg0", targetNamespace = "")
        TdistrictDto arg0);

    /**
     * 
     * @return
     *     returns java.util.List<service.TdistrictDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listDistricts", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.ListDistricts")
    @ResponseWrapper(localName = "listDistrictsResponse", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.ListDistrictsResponse")
    @Action(input = "http://AddressEx.addressService.service.clinicawebservice.com/TdistrictService/listDistrictsRequest", output = "http://AddressEx.addressService.service.clinicawebservice.com/TdistrictService/listDistrictsResponse")
    public List<TdistrictDto> listDistricts();

    /**
     * 
     * @param arg0
     * @return
     *     returns service.TdistrictDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchDistrictById", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.SearchDistrictById")
    @ResponseWrapper(localName = "searchDistrictByIdResponse", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.SearchDistrictByIdResponse")
    @Action(input = "http://AddressEx.addressService.service.clinicawebservice.com/TdistrictService/searchDistrictByIdRequest", output = "http://AddressEx.addressService.service.clinicawebservice.com/TdistrictService/searchDistrictByIdResponse")
    public TdistrictDto searchDistrictById(
        @WebParam(name = "arg0", targetNamespace = "")
        TdistrictDto arg0);

}
