
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TprovinceServiceImplService", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", wsdlLocation = "http://192.168.0.7:7001/TprovinceServiceImpl/TprovinceServiceImplService?WSDL")
public class TprovinceServiceImplService
    extends Service
{

    private final static URL TPROVINCESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TPROVINCESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TPROVINCESERVICEIMPLSERVICE_QNAME = new QName("http://AddressEx.addressService.service.clinicawebservice.com/", "TprovinceServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.7:7001/TprovinceServiceImpl/TprovinceServiceImplService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TPROVINCESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TPROVINCESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TprovinceServiceImplService() {
        super(__getWsdlLocation(), TPROVINCESERVICEIMPLSERVICE_QNAME);
    }

    public TprovinceServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TPROVINCESERVICEIMPLSERVICE_QNAME, features);
    }

    public TprovinceServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TPROVINCESERVICEIMPLSERVICE_QNAME);
    }

    public TprovinceServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TPROVINCESERVICEIMPLSERVICE_QNAME, features);
    }

    public TprovinceServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TprovinceServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TprovinceService
     */
    @WebEndpoint(name = "TprovinceServiceImplPort")
    public TprovinceService getTprovinceServiceImplPort() {
        return super.getPort(new QName("http://AddressEx.addressService.service.clinicawebservice.com/", "TprovinceServiceImplPort"), TprovinceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TprovinceService
     */
    @WebEndpoint(name = "TprovinceServiceImplPort")
    public TprovinceService getTprovinceServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://AddressEx.addressService.service.clinicawebservice.com/", "TprovinceServiceImplPort"), TprovinceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TPROVINCESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TPROVINCESERVICEIMPLSERVICE_EXCEPTION;
        }
        return TPROVINCESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
