
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TprovinceService", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TprovinceService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertProvince", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.InsertProvince")
    @ResponseWrapper(localName = "insertProvinceResponse", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.InsertProvinceResponse")
    @Action(input = "http://AddressEx.addressService.service.clinicawebservice.com/TprovinceService/insertProvinceRequest", output = "http://AddressEx.addressService.service.clinicawebservice.com/TprovinceService/insertProvinceResponse")
    public boolean insertProvince(
        @WebParam(name = "arg0", targetNamespace = "")
        TprovinceDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.TprovinceDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchProvinceById", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.SearchProvinceById")
    @ResponseWrapper(localName = "searchProvinceByIdResponse", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.SearchProvinceByIdResponse")
    @Action(input = "http://AddressEx.addressService.service.clinicawebservice.com/TprovinceService/searchProvinceByIdRequest", output = "http://AddressEx.addressService.service.clinicawebservice.com/TprovinceService/searchProvinceByIdResponse")
    public TprovinceDto searchProvinceById(
        @WebParam(name = "arg0", targetNamespace = "")
        TprovinceDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteProvince", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.DeleteProvince")
    @ResponseWrapper(localName = "deleteProvinceResponse", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.DeleteProvinceResponse")
    @Action(input = "http://AddressEx.addressService.service.clinicawebservice.com/TprovinceService/deleteProvinceRequest", output = "http://AddressEx.addressService.service.clinicawebservice.com/TprovinceService/deleteProvinceResponse")
    public boolean deleteProvince(
        @WebParam(name = "arg0", targetNamespace = "")
        TprovinceDto arg0);

    /**
     * 
     * @return
     *     returns java.util.List<service.TprovinceDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listProvinces", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.ListProvinces")
    @ResponseWrapper(localName = "listProvincesResponse", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.ListProvincesResponse")
    @Action(input = "http://AddressEx.addressService.service.clinicawebservice.com/TprovinceService/listProvincesRequest", output = "http://AddressEx.addressService.service.clinicawebservice.com/TprovinceService/listProvincesResponse")
    public List<TprovinceDto> listProvinces();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateProvince", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.UpdateProvince")
    @ResponseWrapper(localName = "updateProvinceResponse", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.UpdateProvinceResponse")
    @Action(input = "http://AddressEx.addressService.service.clinicawebservice.com/TprovinceService/updateProvinceRequest", output = "http://AddressEx.addressService.service.clinicawebservice.com/TprovinceService/updateProvinceResponse")
    public boolean updateProvince(
        @WebParam(name = "arg0", targetNamespace = "")
        TprovinceDto arg0);

}
