
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TstatusServiceImplService", targetNamespace = "http://statusService.service.clinicawebservice.com/", wsdlLocation = "http://192.168.0.7:7001/TstatusServiceImpl/TstatusServiceImplService?WSDL")
public class TstatusServiceImplService
    extends Service
{

    private final static URL TSTATUSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TSTATUSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TSTATUSSERVICEIMPLSERVICE_QNAME = new QName("http://statusService.service.clinicawebservice.com/", "TstatusServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.7:7001/TstatusServiceImpl/TstatusServiceImplService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TSTATUSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TSTATUSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TstatusServiceImplService() {
        super(__getWsdlLocation(), TSTATUSSERVICEIMPLSERVICE_QNAME);
    }

    public TstatusServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TSTATUSSERVICEIMPLSERVICE_QNAME, features);
    }

    public TstatusServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TSTATUSSERVICEIMPLSERVICE_QNAME);
    }

    public TstatusServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TSTATUSSERVICEIMPLSERVICE_QNAME, features);
    }

    public TstatusServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TstatusServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TstatusService
     */
    @WebEndpoint(name = "TstatusServiceImplPort")
    public TstatusService getTstatusServiceImplPort() {
        return super.getPort(new QName("http://statusService.service.clinicawebservice.com/", "TstatusServiceImplPort"), TstatusService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TstatusService
     */
    @WebEndpoint(name = "TstatusServiceImplPort")
    public TstatusService getTstatusServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://statusService.service.clinicawebservice.com/", "TstatusServiceImplPort"), TstatusService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TSTATUSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TSTATUSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return TSTATUSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
