
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TusuarioRegsServiceImplService", targetNamespace = "http://usersinfoService.service.clinicawebservice.com/", wsdlLocation = "http://192.168.137.1:7001/TusuarioRegsServiceImpl/TusuarioRegsServiceImplService?WSDL")
public class TusuarioRegsServiceImplService
    extends Service
{

    private final static URL TUSUARIOREGSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TUSUARIOREGSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TUSUARIOREGSSERVICEIMPLSERVICE_QNAME = new QName("http://usersinfoService.service.clinicawebservice.com/", "TusuarioRegsServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.137.1:7001/TusuarioRegsServiceImpl/TusuarioRegsServiceImplService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TUSUARIOREGSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TUSUARIOREGSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TusuarioRegsServiceImplService() {
        super(__getWsdlLocation(), TUSUARIOREGSSERVICEIMPLSERVICE_QNAME);
    }

    public TusuarioRegsServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TUSUARIOREGSSERVICEIMPLSERVICE_QNAME, features);
    }

    public TusuarioRegsServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TUSUARIOREGSSERVICEIMPLSERVICE_QNAME);
    }

    public TusuarioRegsServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TUSUARIOREGSSERVICEIMPLSERVICE_QNAME, features);
    }

    public TusuarioRegsServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TusuarioRegsServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TusuarioRegsService
     */
    @WebEndpoint(name = "TusuarioRegsServiceImplPort")
    public TusuarioRegsService getTusuarioRegsServiceImplPort() {
        return super.getPort(new QName("http://usersinfoService.service.clinicawebservice.com/", "TusuarioRegsServiceImplPort"), TusuarioRegsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TusuarioRegsService
     */
    @WebEndpoint(name = "TusuarioRegsServiceImplPort")
    public TusuarioRegsService getTusuarioRegsServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://usersinfoService.service.clinicawebservice.com/", "TusuarioRegsServiceImplPort"), TusuarioRegsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TUSUARIOREGSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TUSUARIOREGSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return TUSUARIOREGSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
