
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TusuarioRegsService", targetNamespace = "http://usersinfoService.service.clinicawebservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TusuarioRegsService {


    /**
     * 
     * @param usuario
     * @return
     *     returns service.TuserregDto
     */
    @WebMethod(operationName = "Search_Usuarios")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Search_Usuarios", targetNamespace = "http://usersinfoService.service.clinicawebservice.com/", className = "service.SearchUsuarios")
    @ResponseWrapper(localName = "Search_UsuariosResponse", targetNamespace = "http://usersinfoService.service.clinicawebservice.com/", className = "service.SearchUsuariosResponse")
    @Action(input = "http://usersinfoService.service.clinicawebservice.com/TusuarioRegsService/Search_UsuariosRequest", output = "http://usersinfoService.service.clinicawebservice.com/TusuarioRegsService/Search_UsuariosResponse")
    public TuserregDto searchUsuarios(
        @WebParam(name = "Usuario", targetNamespace = "")
        TuserregDto usuario);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUserReg", targetNamespace = "http://usersinfoService.service.clinicawebservice.com/", className = "service.UpdateUserReg")
    @ResponseWrapper(localName = "updateUserRegResponse", targetNamespace = "http://usersinfoService.service.clinicawebservice.com/", className = "service.UpdateUserRegResponse")
    @Action(input = "http://usersinfoService.service.clinicawebservice.com/TusuarioRegsService/updateUserRegRequest", output = "http://usersinfoService.service.clinicawebservice.com/TusuarioRegsService/updateUserRegResponse")
    public boolean updateUserReg(
        @WebParam(name = "arg0", targetNamespace = "")
        TuserregDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.TuserregDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateCredencial", targetNamespace = "http://usersinfoService.service.clinicawebservice.com/", className = "service.ValidateCredencial")
    @ResponseWrapper(localName = "validateCredencialResponse", targetNamespace = "http://usersinfoService.service.clinicawebservice.com/", className = "service.ValidateCredencialResponse")
    @Action(input = "http://usersinfoService.service.clinicawebservice.com/TusuarioRegsService/validateCredencialRequest", output = "http://usersinfoService.service.clinicawebservice.com/TusuarioRegsService/validateCredencialResponse")
    public TuserregDto validateCredencial(
        @WebParam(name = "arg0", targetNamespace = "")
        TuserregDto arg0);

    /**
     * 
     * @return
     *     returns java.util.List<service.TuserregDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listUsersRegs", targetNamespace = "http://usersinfoService.service.clinicawebservice.com/", className = "service.ListUsersRegs")
    @ResponseWrapper(localName = "listUsersRegsResponse", targetNamespace = "http://usersinfoService.service.clinicawebservice.com/", className = "service.ListUsersRegsResponse")
    @Action(input = "http://usersinfoService.service.clinicawebservice.com/TusuarioRegsService/listUsersRegsRequest", output = "http://usersinfoService.service.clinicawebservice.com/TusuarioRegsService/listUsersRegsResponse")
    public List<TuserregDto> listUsersRegs();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteUserReg", targetNamespace = "http://usersinfoService.service.clinicawebservice.com/", className = "service.DeleteUserReg")
    @ResponseWrapper(localName = "deleteUserRegResponse", targetNamespace = "http://usersinfoService.service.clinicawebservice.com/", className = "service.DeleteUserRegResponse")
    @Action(input = "http://usersinfoService.service.clinicawebservice.com/TusuarioRegsService/deleteUserRegRequest", output = "http://usersinfoService.service.clinicawebservice.com/TusuarioRegsService/deleteUserRegResponse")
    public boolean deleteUserReg(
        @WebParam(name = "arg0", targetNamespace = "")
        TuserregDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertUsersRegs", targetNamespace = "http://usersinfoService.service.clinicawebservice.com/", className = "service.InsertUsersRegs")
    @ResponseWrapper(localName = "insertUsersRegsResponse", targetNamespace = "http://usersinfoService.service.clinicawebservice.com/", className = "service.InsertUsersRegsResponse")
    @Action(input = "http://usersinfoService.service.clinicawebservice.com/TusuarioRegsService/insertUsersRegsRequest", output = "http://usersinfoService.service.clinicawebservice.com/TusuarioRegsService/insertUsersRegsResponse")
    public boolean insertUsersRegs(
        @WebParam(name = "arg0", targetNamespace = "")
        TuserregDto arg0);

}
