
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TvillageService", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TvillageService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteVillage", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.DeleteVillage")
    @ResponseWrapper(localName = "deleteVillageResponse", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.DeleteVillageResponse")
    @Action(input = "http://AddressEx.addressService.service.clinicawebservice.com/TvillageService/deleteVillageRequest", output = "http://AddressEx.addressService.service.clinicawebservice.com/TvillageService/deleteVillageResponse")
    public boolean deleteVillage(
        @WebParam(name = "arg0", targetNamespace = "")
        TvillageDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.TvillageDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchVillageById", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.SearchVillageById")
    @ResponseWrapper(localName = "searchVillageByIdResponse", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.SearchVillageByIdResponse")
    @Action(input = "http://AddressEx.addressService.service.clinicawebservice.com/TvillageService/searchVillageByIdRequest", output = "http://AddressEx.addressService.service.clinicawebservice.com/TvillageService/searchVillageByIdResponse")
    public TvillageDto searchVillageById(
        @WebParam(name = "arg0", targetNamespace = "")
        TvillageDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertVillage", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.InsertVillage")
    @ResponseWrapper(localName = "insertVillageResponse", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.InsertVillageResponse")
    @Action(input = "http://AddressEx.addressService.service.clinicawebservice.com/TvillageService/insertVillageRequest", output = "http://AddressEx.addressService.service.clinicawebservice.com/TvillageService/insertVillageResponse")
    public boolean insertVillage(
        @WebParam(name = "arg0", targetNamespace = "")
        TvillageDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateVillage", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.UpdateVillage")
    @ResponseWrapper(localName = "updateVillageResponse", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.UpdateVillageResponse")
    @Action(input = "http://AddressEx.addressService.service.clinicawebservice.com/TvillageService/updateVillageRequest", output = "http://AddressEx.addressService.service.clinicawebservice.com/TvillageService/updateVillageResponse")
    public boolean updateVillage(
        @WebParam(name = "arg0", targetNamespace = "")
        TvillageDto arg0);

    /**
     * 
     * @return
     *     returns java.util.List<service.TvillageDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listVillages", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.ListVillages")
    @ResponseWrapper(localName = "listVillagesResponse", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", className = "service.ListVillagesResponse")
    @Action(input = "http://AddressEx.addressService.service.clinicawebservice.com/TvillageService/listVillagesRequest", output = "http://AddressEx.addressService.service.clinicawebservice.com/TvillageService/listVillagesResponse")
    public List<TvillageDto> listVillages();

}
