
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TvillageServiceImplService", targetNamespace = "http://AddressEx.addressService.service.clinicawebservice.com/", wsdlLocation = "http://192.168.137.1:7001/TvillageServiceImpl/TvillageServiceImplService?WSDL")
public class TvillageServiceImplService
    extends Service
{

    private final static URL TVILLAGESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TVILLAGESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TVILLAGESERVICEIMPLSERVICE_QNAME = new QName("http://AddressEx.addressService.service.clinicawebservice.com/", "TvillageServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.137.1:7001/TvillageServiceImpl/TvillageServiceImplService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TVILLAGESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TVILLAGESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TvillageServiceImplService() {
        super(__getWsdlLocation(), TVILLAGESERVICEIMPLSERVICE_QNAME);
    }

    public TvillageServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TVILLAGESERVICEIMPLSERVICE_QNAME, features);
    }

    public TvillageServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TVILLAGESERVICEIMPLSERVICE_QNAME);
    }

    public TvillageServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TVILLAGESERVICEIMPLSERVICE_QNAME, features);
    }

    public TvillageServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TvillageServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TvillageService
     */
    @WebEndpoint(name = "TvillageServiceImplPort")
    public TvillageService getTvillageServiceImplPort() {
        return super.getPort(new QName("http://AddressEx.addressService.service.clinicawebservice.com/", "TvillageServiceImplPort"), TvillageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TvillageService
     */
    @WebEndpoint(name = "TvillageServiceImplPort")
    public TvillageService getTvillageServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://AddressEx.addressService.service.clinicawebservice.com/", "TvillageServiceImplPort"), TvillageService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TVILLAGESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TVILLAGESERVICEIMPLSERVICE_EXCEPTION;
        }
        return TVILLAGESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
