
package com.clinicacliente.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TdistrictServiceImplService", targetNamespace = "http://AddressEx.addressService.service.cliniacajavaee.com/", wsdlLocation = "http://192.168.137.1:7001/TdistrictServiceImpl/TdistrictServiceImplService?WSDL")
public class TdistrictServiceImplService
    extends Service
{

    private final static URL TDISTRICTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TDISTRICTSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TDISTRICTSERVICEIMPLSERVICE_QNAME = new QName("http://AddressEx.addressService.service.cliniacajavaee.com/", "TdistrictServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.137.1:7001/TdistrictServiceImpl/TdistrictServiceImplService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TDISTRICTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TDISTRICTSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TdistrictServiceImplService() {
        super(__getWsdlLocation(), TDISTRICTSERVICEIMPLSERVICE_QNAME);
    }

    public TdistrictServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TDISTRICTSERVICEIMPLSERVICE_QNAME, features);
    }

    public TdistrictServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TDISTRICTSERVICEIMPLSERVICE_QNAME);
    }

    public TdistrictServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TDISTRICTSERVICEIMPLSERVICE_QNAME, features);
    }

    public TdistrictServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TdistrictServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TdistrictService
     */
    @WebEndpoint(name = "TdistrictServiceImplPort")
    public TdistrictService getTdistrictServiceImplPort() {
        return super.getPort(new QName("http://AddressEx.addressService.service.cliniacajavaee.com/", "TdistrictServiceImplPort"), TdistrictService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TdistrictService
     */
    @WebEndpoint(name = "TdistrictServiceImplPort")
    public TdistrictService getTdistrictServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://AddressEx.addressService.service.cliniacajavaee.com/", "TdistrictServiceImplPort"), TdistrictService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TDISTRICTSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TDISTRICTSERVICEIMPLSERVICE_EXCEPTION;
        }
        return TDISTRICTSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
