
package com.clinicacliente.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TstatusService", targetNamespace = "http://statusService.service.cliniacajavaee.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TstatusService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "UPDATE_STATUS")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "UPDATE_STATUS", targetNamespace = "http://statusService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.UPDATESTATUS")
    @ResponseWrapper(localName = "UPDATE_STATUSResponse", targetNamespace = "http://statusService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.UPDATESTATUSResponse")
    @Action(input = "http://statusService.service.cliniacajavaee.com/TstatusService/UPDATE_STATUSRequest", output = "http://statusService.service.cliniacajavaee.com/TstatusService/UPDATE_STATUSResponse")
    public boolean updateSTATUS(
        @WebParam(name = "arg0", targetNamespace = "")
        TstatusDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.clinicacliente.service.TstatusDto
     */
    @WebMethod(operationName = "SEARCH_STATUS")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SEARCH_STATUS", targetNamespace = "http://statusService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.SEARCHSTATUS")
    @ResponseWrapper(localName = "SEARCH_STATUSResponse", targetNamespace = "http://statusService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.SEARCHSTATUSResponse")
    @Action(input = "http://statusService.service.cliniacajavaee.com/TstatusService/SEARCH_STATUSRequest", output = "http://statusService.service.cliniacajavaee.com/TstatusService/SEARCH_STATUSResponse")
    public TstatusDto searchSTATUS(
        @WebParam(name = "arg0", targetNamespace = "")
        TstatusDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "INSERT_STATUS")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "INSERT_STATUS", targetNamespace = "http://statusService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.INSERTSTATUS")
    @ResponseWrapper(localName = "INSERT_STATUSResponse", targetNamespace = "http://statusService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.INSERTSTATUSResponse")
    @Action(input = "http://statusService.service.cliniacajavaee.com/TstatusService/INSERT_STATUSRequest", output = "http://statusService.service.cliniacajavaee.com/TstatusService/INSERT_STATUSResponse")
    public boolean insertSTATUS(
        @WebParam(name = "arg0", targetNamespace = "")
        TstatusDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "DELETE_STATUS")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "DELETE_STATUS", targetNamespace = "http://statusService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.DELETESTATUS")
    @ResponseWrapper(localName = "DELETE_STATUSResponse", targetNamespace = "http://statusService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.DELETESTATUSResponse")
    @Action(input = "http://statusService.service.cliniacajavaee.com/TstatusService/DELETE_STATUSRequest", output = "http://statusService.service.cliniacajavaee.com/TstatusService/DELETE_STATUSResponse")
    public boolean deleteSTATUS(
        @WebParam(name = "arg0", targetNamespace = "")
        TstatusDto arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.clinicacliente.service.TstatusDto>
     */
    @WebMethod(operationName = "LIST_ALL_STATUS")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "LIST_ALL_STATUS", targetNamespace = "http://statusService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.LISTALLSTATUS")
    @ResponseWrapper(localName = "LIST_ALL_STATUSResponse", targetNamespace = "http://statusService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.LISTALLSTATUSResponse")
    @Action(input = "http://statusService.service.cliniacajavaee.com/TstatusService/LIST_ALL_STATUSRequest", output = "http://statusService.service.cliniacajavaee.com/TstatusService/LIST_ALL_STATUSResponse")
    public List<TstatusDto> listALLSTATUS();

}
