
package com.clinicacliente.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TtypeUserServiceImplService", targetNamespace = "http://typeUserService.usersinfoService.service.cliniacajavaee.com/", wsdlLocation = "http://192.168.137.1:7001/TtypeUserServiceImpl/TtypeUserServiceImplService?WSDL")
public class TtypeUserServiceImplService
    extends Service
{

    private final static URL TTYPEUSERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TTYPEUSERSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TTYPEUSERSERVICEIMPLSERVICE_QNAME = new QName("http://typeUserService.usersinfoService.service.cliniacajavaee.com/", "TtypeUserServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.137.1:7001/TtypeUserServiceImpl/TtypeUserServiceImplService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TTYPEUSERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TTYPEUSERSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TtypeUserServiceImplService() {
        super(__getWsdlLocation(), TTYPEUSERSERVICEIMPLSERVICE_QNAME);
    }

    public TtypeUserServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TTYPEUSERSERVICEIMPLSERVICE_QNAME, features);
    }

    public TtypeUserServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TTYPEUSERSERVICEIMPLSERVICE_QNAME);
    }

    public TtypeUserServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TTYPEUSERSERVICEIMPLSERVICE_QNAME, features);
    }

    public TtypeUserServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TtypeUserServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TtypeUserService
     */
    @WebEndpoint(name = "TtypeUserServiceImplPort")
    public TtypeUserService getTtypeUserServiceImplPort() {
        return super.getPort(new QName("http://typeUserService.usersinfoService.service.cliniacajavaee.com/", "TtypeUserServiceImplPort"), TtypeUserService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TtypeUserService
     */
    @WebEndpoint(name = "TtypeUserServiceImplPort")
    public TtypeUserService getTtypeUserServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://typeUserService.usersinfoService.service.cliniacajavaee.com/", "TtypeUserServiceImplPort"), TtypeUserService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TTYPEUSERSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TTYPEUSERSERVICEIMPLSERVICE_EXCEPTION;
        }
        return TTYPEUSERSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
