
package com.clinicacliente.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TuserTypeRegsServiceImplService", targetNamespace = "http://typeUserService.usersinfoService.service.cliniacajavaee.com/", wsdlLocation = "http://192.168.137.1:7001/TuserTypeRegsServiceImpl/TuserTypeRegsServiceImplService?WSDL")
public class TuserTypeRegsServiceImplService
    extends Service
{

    private final static URL TUSERTYPEREGSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TUSERTYPEREGSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TUSERTYPEREGSSERVICEIMPLSERVICE_QNAME = new QName("http://typeUserService.usersinfoService.service.cliniacajavaee.com/", "TuserTypeRegsServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.137.1:7001/TuserTypeRegsServiceImpl/TuserTypeRegsServiceImplService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TUSERTYPEREGSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TUSERTYPEREGSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TuserTypeRegsServiceImplService() {
        super(__getWsdlLocation(), TUSERTYPEREGSSERVICEIMPLSERVICE_QNAME);
    }

    public TuserTypeRegsServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TUSERTYPEREGSSERVICEIMPLSERVICE_QNAME, features);
    }

    public TuserTypeRegsServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TUSERTYPEREGSSERVICEIMPLSERVICE_QNAME);
    }

    public TuserTypeRegsServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TUSERTYPEREGSSERVICEIMPLSERVICE_QNAME, features);
    }

    public TuserTypeRegsServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TuserTypeRegsServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TuserTypeRegsService
     */
    @WebEndpoint(name = "TuserTypeRegsServiceImplPort")
    public TuserTypeRegsService getTuserTypeRegsServiceImplPort() {
        return super.getPort(new QName("http://typeUserService.usersinfoService.service.cliniacajavaee.com/", "TuserTypeRegsServiceImplPort"), TuserTypeRegsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TuserTypeRegsService
     */
    @WebEndpoint(name = "TuserTypeRegsServiceImplPort")
    public TuserTypeRegsService getTuserTypeRegsServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://typeUserService.usersinfoService.service.cliniacajavaee.com/", "TuserTypeRegsServiceImplPort"), TuserTypeRegsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TUSERTYPEREGSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TUSERTYPEREGSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return TUSERTYPEREGSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
