
package com.clinicacliente.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TusuarioRegsService", targetNamespace = "http://usersinfoService.service.cliniacajavaee.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TusuarioRegsService {


    /**
     * 
     * @return
     *     returns java.util.List<com.clinicacliente.service.TusuarioregDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listUsersRegs", targetNamespace = "http://usersinfoService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.ListUsersRegs")
    @ResponseWrapper(localName = "listUsersRegsResponse", targetNamespace = "http://usersinfoService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.ListUsersRegsResponse")
    @Action(input = "http://usersinfoService.service.cliniacajavaee.com/TusuarioRegsService/listUsersRegsRequest", output = "http://usersinfoService.service.cliniacajavaee.com/TusuarioRegsService/listUsersRegsResponse")
    public List<TusuarioregDto> listUsersRegs();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUserReg", targetNamespace = "http://usersinfoService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.UpdateUserReg")
    @ResponseWrapper(localName = "updateUserRegResponse", targetNamespace = "http://usersinfoService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.UpdateUserRegResponse")
    @Action(input = "http://usersinfoService.service.cliniacajavaee.com/TusuarioRegsService/updateUserRegRequest", output = "http://usersinfoService.service.cliniacajavaee.com/TusuarioRegsService/updateUserRegResponse")
    public boolean updateUserReg(
        @WebParam(name = "arg0", targetNamespace = "")
        TusuarioregDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteUserReg", targetNamespace = "http://usersinfoService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.DeleteUserReg")
    @ResponseWrapper(localName = "deleteUserRegResponse", targetNamespace = "http://usersinfoService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.DeleteUserRegResponse")
    @Action(input = "http://usersinfoService.service.cliniacajavaee.com/TusuarioRegsService/deleteUserRegRequest", output = "http://usersinfoService.service.cliniacajavaee.com/TusuarioRegsService/deleteUserRegResponse")
    public boolean deleteUserReg(
        @WebParam(name = "arg0", targetNamespace = "")
        TusuarioregDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertUsersRegs", targetNamespace = "http://usersinfoService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.InsertUsersRegs")
    @ResponseWrapper(localName = "insertUsersRegsResponse", targetNamespace = "http://usersinfoService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.InsertUsersRegsResponse")
    @Action(input = "http://usersinfoService.service.cliniacajavaee.com/TusuarioRegsService/insertUsersRegsRequest", output = "http://usersinfoService.service.cliniacajavaee.com/TusuarioRegsService/insertUsersRegsResponse")
    public boolean insertUsersRegs(
        @WebParam(name = "arg0", targetNamespace = "")
        TusuarioregDto arg0);

    /**
     * 
     * @param usuario
     * @return
     *     returns com.clinicacliente.service.TusuarioregDto
     */
    @WebMethod(operationName = "Search_Usuarios")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Search_Usuarios", targetNamespace = "http://usersinfoService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.SearchUsuarios")
    @ResponseWrapper(localName = "Search_UsuariosResponse", targetNamespace = "http://usersinfoService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.SearchUsuariosResponse")
    @Action(input = "http://usersinfoService.service.cliniacajavaee.com/TusuarioRegsService/Search_UsuariosRequest", output = "http://usersinfoService.service.cliniacajavaee.com/TusuarioRegsService/Search_UsuariosResponse")
    public TusuarioregDto searchUsuarios(
        @WebParam(name = "Usuario", targetNamespace = "")
        TusuarioregDto usuario);

}
