
package com.clinicacliente.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TvillageService", targetNamespace = "http://AddressEx.addressService.service.cliniacajavaee.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TvillageService {


    /**
     * 
     * @return
     *     returns java.util.List<com.clinicacliente.service.TvillageDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listVillages", targetNamespace = "http://AddressEx.addressService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.ListVillages")
    @ResponseWrapper(localName = "listVillagesResponse", targetNamespace = "http://AddressEx.addressService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.ListVillagesResponse")
    @Action(input = "http://AddressEx.addressService.service.cliniacajavaee.com/TvillageService/listVillagesRequest", output = "http://AddressEx.addressService.service.cliniacajavaee.com/TvillageService/listVillagesResponse")
    public List<TvillageDto> listVillages();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteProvince", targetNamespace = "http://AddressEx.addressService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.DeleteProvince")
    @ResponseWrapper(localName = "deleteProvinceResponse", targetNamespace = "http://AddressEx.addressService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.DeleteProvinceResponse")
    @Action(input = "http://AddressEx.addressService.service.cliniacajavaee.com/TvillageService/deleteProvinceRequest", output = "http://AddressEx.addressService.service.cliniacajavaee.com/TvillageService/deleteProvinceResponse")
    public boolean deleteProvince(
        @WebParam(name = "arg0", targetNamespace = "")
        TvillageDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.clinicacliente.service.TvillageDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchVillageById", targetNamespace = "http://AddressEx.addressService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.SearchVillageById")
    @ResponseWrapper(localName = "searchVillageByIdResponse", targetNamespace = "http://AddressEx.addressService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.SearchVillageByIdResponse")
    @Action(input = "http://AddressEx.addressService.service.cliniacajavaee.com/TvillageService/searchVillageByIdRequest", output = "http://AddressEx.addressService.service.cliniacajavaee.com/TvillageService/searchVillageByIdResponse")
    public TvillageDto searchVillageById(
        @WebParam(name = "arg0", targetNamespace = "")
        TvillageDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertVillage", targetNamespace = "http://AddressEx.addressService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.InsertVillage")
    @ResponseWrapper(localName = "insertVillageResponse", targetNamespace = "http://AddressEx.addressService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.InsertVillageResponse")
    @Action(input = "http://AddressEx.addressService.service.cliniacajavaee.com/TvillageService/insertVillageRequest", output = "http://AddressEx.addressService.service.cliniacajavaee.com/TvillageService/insertVillageResponse")
    public boolean insertVillage(
        @WebParam(name = "arg0", targetNamespace = "")
        TvillageDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateVillage", targetNamespace = "http://AddressEx.addressService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.UpdateVillage")
    @ResponseWrapper(localName = "updateVillageResponse", targetNamespace = "http://AddressEx.addressService.service.cliniacajavaee.com/", className = "com.clinicacliente.service.UpdateVillageResponse")
    @Action(input = "http://AddressEx.addressService.service.cliniacajavaee.com/TvillageService/updateVillageRequest", output = "http://AddressEx.addressService.service.cliniacajavaee.com/TvillageService/updateVillageResponse")
    public boolean updateVillage(
        @WebParam(name = "arg0", targetNamespace = "")
        TvillageDto arg0);

}
